import type { Metadata } from "next";
import "@turbotemplate/ui/globals.css";
import { enUS } from "@clerk/localizations";
import { ClerkLoaded, ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/themes";
import { TooltipProvider } from "@turbotemplate/ui/components/ui/tooltip";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const marketingUrl = process.env.NEXT_PUBLIC_MARKETING_URL || "/";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      afterSignOutUrl={marketingUrl}
      signInUrl="/app/sign-in"
      signUpUrl="/app/sign-up"
      signInFallbackRedirectUrl="/app"
      signUpFallbackRedirectUrl="/app"
      localization={enUS}
      appearance={{
        baseTheme: shadcn,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            storageKey="turbotemplate-theme"
            disableTransitionOnChange
          >
            <ClerkLoaded>
              <TooltipProvider>
                <ConvexClientProvider>{children}</ConvexClientProvider>
              </TooltipProvider>
            </ClerkLoaded>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
